GET http://localhost:8080/api/workitem?year=2023&month=12 HTTP/1.1
Accept: application/json

###

POST http://localhost:8080/api/workitem HTTP/1.1
Content-Type: application/json

{
  "name": "Example work item with init total duration",
  "period_month": 2024,
  "period_year": 1,
  "init_total_duration_in_seconds": 12
}

###

PATCH http://localhost:8080/api/workitem/4/start HTTP/1.1

###

PATCH http://localhost:8080/api/workitem/stop HTTP/1.1

###

DELETE http://localhost:8080/api/workitem/3 HTTP/1.1